<?php

namespace App\Exports;

use App\Models\ExpenditureCategory;
use App\Models\School;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

class BudgetExpenditureExport implements WithEvents, WithTitle
{
    private string $academicYear;
    private array  $filters;
    private array  $site;

    public function __construct(string $academicYear, array $filters, array $site)
    {
        $this->academicYear = $academicYear;
        $this->filters      = $filters;
        $this->site         = $site;
    }

    public function title(): string
    {
        return 'Expenditure';
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet      = $event->sheet->getDelegate();
                $divisionId = $this->filters['division_id'] ?? null;
                $schoolId   = $this->filters['school_id']   ?? null;

                // ── Branding rows ──────────────────────────────────
                $sheet->mergeCells('A1:E1');
                $sheet->getCell('A1')->setValue($this->site['site_name_en']);
                $sheet->getStyle('A1')->applyFromArray(['font' => ['bold' => true, 'size' => 14, 'color' => ['rgb' => '1e1b4b']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A2:E2');
                $sheet->getCell('A2')->setValue($this->site['site_name_si']);
                $sheet->getStyle('A2')->applyFromArray(['font' => ['size' => 11, 'color' => ['rgb' => '4b5563']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A3:E3');
                $sheet->getCell('A3')->setValue('Budget Analysis — Estimated Expenditure (' . $this->academicYear . ')');
                $sheet->getStyle('A3')->applyFromArray(['font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => '4f46e5']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A4:E4');
                $sheet->getCell('A4')->setValue('Generated by: ' . $this->site['generated_by'] . ' | ' . $this->site['generated_at']);
                $sheet->getStyle('A4')->applyFromArray(['font' => ['size' => 9, 'italic' => true, 'color' => ['rgb' => '9ca3af']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);

                // ── Header row ──────────────────────────────────────
                $row = 6;
                $sheet->getCell("A{$row}")->setValue('School');
                $sheet->getCell("B{$row}")->setValue('Division');
                $sheet->getCell("C{$row}")->setValue('Expenditure Category');
                $sheet->getCell("D{$row}")->setValue('Expenditure Vote');
                $sheet->getCell("E{$row}")->setValue('Expected Amount (Rs.)');
                $sheet->getStyle("A{$row}:E{$row}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 10],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'dc2626']],
                ]);
                $row++;

                // ── Data rows ─────────────────────────────────────
                $schools = School::with(['division'])
                    ->where('is_active', true)
                    ->when($divisionId, fn ($q) => $q->where('division_id', $divisionId))
                    ->when($schoolId,   fn ($q) => $q->where('id', $schoolId))
                    ->orderBy('name_en')->get();

                $categories = ExpenditureCategory::with('votes')->orderBy('label_en')->get();

                foreach ($schools as $school) {
                    $expenditures = \App\Models\SchoolBudgetExpenditure::where('school_id', $school->id)
                        ->where('academic_year', $this->academicYear)
                        ->pluck('expected_amount', 'expenditure_vote_id');

                    if ($expenditures->isEmpty()) {
                        continue;
                    }

                    foreach ($categories as $category) {
                        foreach ($category->votes as $vote) {
                            if (!isset($expenditures[$vote->id]) || (float) $expenditures[$vote->id] <= 0) {
                                continue;
                            }

                            $sheet->getCell("A{$row}")->setValue($school->name_en);
                            $sheet->getCell("B{$row}")->setValue($school->division?->name_en ?? '—');
                            $sheet->getCell("C{$row}")->setValue($category->label_en);
                            $sheet->getCell("D{$row}")->setValue($vote->label_en);
                            $sheet->getCell("E{$row}")->setValue((float) $expenditures[$vote->id]);

                            $sheet->getStyle("A{$row}:E{$row}")->applyFromArray([
                                'font'    => ['size' => 10],
                                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'e5e7eb']]],
                            ]);
                            $row++;
                        }
                    }
                }

                $sheet->getColumnDimension('A')->setWidth(30);
                $sheet->getColumnDimension('B')->setWidth(20);
                $sheet->getColumnDimension('C')->setWidth(24);
                $sheet->getColumnDimension('D')->setWidth(28);
                $sheet->getColumnDimension('E')->setWidth(20);
                $sheet->freezePane('A7');
            },
        ];
    }
}
