<?php

namespace App\Exports;

use App\Models\School;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

class PhysicalResourcesMapExport implements WithEvents, WithTitle
{
    private string $facility;
    private array $filters;
    private array $site;

    private array $facilityLabels = [
        'library' => 'Library', 'staff_room' => 'Staff Room', 'administrative_block' => 'Admin Block',
        'hostel' => 'Hostel', 'teachers_quarters' => 'Teachers Quarters', 'principals_quarters' => 'Principals Quarters',
        'canteen' => 'Canteen', 'multi_story_buildings' => 'Multi-Story Buildings',
        'electricity' => 'Electricity', 'drinking_water' => 'Drinking Water', 'hand_washing' => 'Hand Washing',
        'solar_power' => 'Solar Power', 'waste_management' => 'Waste Management',
        'computer_lab' => 'Computer Lab', 'internet_access' => 'Internet Access', 'wifi' => 'WiFi',
        'school_mis' => 'School MIS', 'cctv' => 'CCTV', 'digital_attendance' => 'Digital Attendance',
        'science_lab' => 'Science Lab', 'home_economics_unit' => 'Home Economics', 'music_room' => 'Music Room',
        'dancing_room' => 'Dancing Room', 'playground' => 'Playground', 'volleyball_court' => 'Volleyball Court',
        'netball_court' => 'Netball Court', 'athletic_track' => 'Athletic Track',
        'cctv_monitoring' => 'CCTV Monitoring', 'security_fence' => 'Security Fence',
        'fire_extinguishers' => 'Fire Extinguishers', 'emergency_exit_plan' => 'Emergency Exit Plan',
        'disaster_preparedness' => 'Disaster Preparedness', 'student_safety_committee' => 'Safety Committee',
        'public_transport_access' => 'Public Transport', 'school_van' => 'School Van',
        'disabled_accessibility' => 'Disabled Accessibility',
    ];

    public function __construct(string $facility, array $filters, array $site)
    {
        $this->facility = $facility;
        $this->filters  = $filters;
        $this->site     = $site;
    }

    public function title(): string
    {
        return 'Map - ' . ($this->facilityLabels[$this->facility] ?? $this->facility);
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet      = $event->sheet->getDelegate();
                $divisionId = $this->filters['division_id'] ?? null;
                $schoolId   = $this->filters['school_id']   ?? null;
                $facility   = $this->facility;
                $label      = $this->facilityLabels[$facility] ?? $facility;

                // Branding
                $sheet->mergeCells('A1:D1');
                $sheet->getCell('A1')->setValue($this->site['site_name_en']);
                $sheet->getStyle('A1')->applyFromArray(['font' => ['bold' => true, 'size' => 14, 'color' => ['rgb' => '1e1b4b']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A2:D2');
                $sheet->getCell('A2')->setValue($this->site['site_name_si']);
                $sheet->getStyle('A2')->applyFromArray(['font' => ['size' => 11, 'color' => ['rgb' => '4b5563']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A3:D3');
                $sheet->getCell('A3')->setValue('Facility Map — ' . $label);
                $sheet->getStyle('A3')->applyFromArray(['font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => '4f46e5']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);
                $sheet->mergeCells('A4:D4');
                $sheet->getCell('A4')->setValue('Generated by: ' . $this->site['generated_by'] . ' | ' . $this->site['generated_at']);
                $sheet->getStyle('A4')->applyFromArray(['font' => ['size' => 9, 'italic' => true, 'color' => ['rgb' => '9ca3af']], 'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]]);

                $row = 6;
                $sheet->getCell("A{$row}")->setValue('School');
                $sheet->getCell("B{$row}")->setValue('Division');
                $sheet->getCell("C{$row}")->setValue('Type');
                $sheet->getCell("D{$row}")->setValue('Status: ' . $label);
                $sheet->getStyle("A{$row}:D{$row}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 10],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4f46e5']],
                ]);
                $row++;

                $schools = School::with(['division', 'physicalResources'])
                    ->where('is_active', true)
                    ->when($divisionId, fn($q) => $q->where('division_id', $divisionId))
                    ->when($schoolId,   fn($q) => $q->where('id', $schoolId))
                    ->orderBy('name_en')->get();

                foreach ($schools as $school) {
                    $res = $school->physicalResources;
                    $status = !$res ? 'Not Submitted' : ($res->$facility ? 'Yes' : 'No');
                    $bg = match($status) {
                        'Yes' => 'ecfdf5', 'No' => 'fef2f2', default => 'f3f4f6',
                    };
                    foreach (['A' => $school->name_en, 'B' => $school->division?->name_en, 'C' => $school->type, 'D' => $status] as $col => $val) {
                        $sheet->getCell("{$col}{$row}")->setValue($val);
                        $sheet->getStyle("{$col}{$row}")->applyFromArray([
                            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bg]],
                            'font' => ['size' => 10],
                            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'e5e7eb']]],
                        ]);
                    }
                    $row++;
                }

                foreach (['A' => 30, 'B' => 22, 'C' => 12, 'D' => 18] as $col => $width) {
                    $sheet->getColumnDimension($col)->setWidth($width);
                }
                $sheet->freezePane('A7');
            },
        ];
    }
}