<?php

namespace App\Exports;

use App\Models\Division;
use App\Models\School;
use App\Models\SchoolStat;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

class StudentsAnalysisExport implements WithEvents, WithTitle
{
    private array $filters;
    private array $site;

    public function __construct(array $filters, array $site)
    {
        $this->filters = $filters;
        $this->site    = $site;
    }

    public function title(): string
    {
        return 'Student Analysis';
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();

                $divId        = $this->filters['division_id']   ?? null;
                $schoolId     = $this->filters['school_id']     ?? null;
                $academicYear = $this->filters['academic_year'] ?? null;

                $grades   = range(1, 13);
                $boyCols  = array_map(fn($g) => "grade_{$g}_boys",  $grades);
                $girlCols = array_map(fn($g) => "grade_{$g}_girls", $grades);
                $allCols  = array_merge($boyCols, $girlCols, ['disabled_boys', 'disabled_girls']);

                $base = fn() => SchoolStat::query()
                    ->when($divId,        fn($q) => $q->whereHas('school', fn($q) => $q->where('division_id', $divId)))
                    ->when($schoolId,     fn($q) => $q->where('school_id', $schoolId))
                    ->when($academicYear, fn($q) => $q->where('academic_year', $academicYear));

                // ── Branding header ───────────────────────────────────
                $sheet->mergeCells('A1:G1');
                $sheet->getCell('A1')->setValue($this->site['site_name_en']);
                $sheet->getStyle('A1')->applyFromArray([
                    'font'      => ['bold' => true, 'size' => 14, 'color' => ['rgb' => '1e1b4b']],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);
                $sheet->mergeCells('A2:G2');
                $sheet->getCell('A2')->setValue($this->site['site_name_si']);
                $sheet->getStyle('A2')->applyFromArray([
                    'font'      => ['size' => 11, 'color' => ['rgb' => '4b5563']],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);
                $sheet->mergeCells('A3:G3');
                $sheet->getCell('A3')->setValue('Student Analysis Report — ' . ($academicYear ?? 'All Years'));
                $sheet->getStyle('A3')->applyFromArray([
                    'font'      => ['bold' => true, 'size' => 11, 'color' => ['rgb' => '4f46e5']],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);
                $sheet->mergeCells('A4:G4');
                $sheet->getCell('A4')->setValue('Generated by: ' . $this->site['generated_by'] . ' | ' . $this->site['generated_at']);
                $sheet->getStyle('A4')->applyFromArray([
                    'font'      => ['size' => 9, 'italic' => true, 'color' => ['rgb' => '9ca3af']],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);

                // ── Section 1: Summary ────────────────────────────────
                $row = 6;
                $sheet->mergeCells("A{$row}:G{$row}");
                $sheet->getCell("A{$row}")->setValue('SUMMARY');
                $sheet->getStyle("A{$row}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 11],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4f46e5']],
                ]);
                $row++;

                $sumExpr = implode(', ', array_map(fn($c) => "COALESCE(SUM($c),0) as $c", $allCols));
                $sums    = (clone $base())->selectRaw($sumExpr)->first();
                $totalBoys  = $sums ? collect($boyCols)->sum(fn($c)  => $sums->$c) : 0;
                $totalGirls = $sums ? collect($girlCols)->sum(fn($c) => $sums->$c) : 0;
                $total      = $totalBoys + $totalGirls;
                $disabled   = $sums ? ($sums->disabled_boys + $sums->disabled_girls) : 0;

                $summaryData = [
                    ['Total Students', $total],
                    ['Boys', $totalBoys],
                    ['Girls', $totalGirls],
                    ['M:F Ratio', $totalGirls > 0 ? round($totalBoys / $totalGirls, 2) . ':1' : 'N/A'],
                    ['Special Needs', $disabled],
                ];
                foreach ($summaryData as $i => [$label, $value]) {
                    $bg = $i % 2 === 0 ? 'f0f4ff' : 'ffffff';
                    $sheet->getCell("A{$row}")->setValue($label);
                    $sheet->getCell("B{$row}")->setValue($value);
                    $sheet->getStyle("A{$row}:B{$row}")->applyFromArray([
                        'fill'    => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bg]],
                        'font'    => ['size' => 10],
                        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'e5e7eb']]],
                    ]);
                    $row++;
                }

                // ── Section 2: By Grade ───────────────────────────────
                $row += 2;
                $sheet->mergeCells("A{$row}:G{$row}");
                $sheet->getCell("A{$row}")->setValue('BY GRADE');
                $sheet->getStyle("A{$row}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 11],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4f46e5']],
                ]);
                $row++;

                // Heading row
                foreach (['A' => 'Grade', 'B' => 'Boys', 'C' => 'Girls', 'D' => 'Total'] as $col => $label) {
                    $sheet->getCell("{$col}{$row}")->setValue($label);
                    $sheet->getStyle("{$col}{$row}")->applyFromArray([
                        'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 10],
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '6366f1']],
                        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'ffffff']]],
                    ]);
                    $sheet->getColumnDimension($col)->setWidth(18);
                }
                $row++;

                $gradeTotal = [0, 0, 0];
                foreach ($grades as $g) {
                    $bc = "grade_{$g}_boys";
                    $gc = "grade_{$g}_girls";
                    $s  = (clone $base())->selectRaw("COALESCE(SUM($bc),0) as boys, COALESCE(SUM($gc),0) as girls")->first();
                    $boys  = $s ? $s->boys  : 0;
                    $girls = $s ? $s->girls : 0;
                    $bg = $row % 2 === 0 ? 'f0f4ff' : 'ffffff';
                    foreach (['A' => "Grade {$g}", 'B' => $boys, 'C' => $girls, 'D' => $boys + $girls] as $col => $val) {
                        $sheet->getCell("{$col}{$row}")->setValue($val);
                        $sheet->getStyle("{$col}{$row}")->applyFromArray([
                            'fill'    => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bg]],
                            'font'    => ['size' => 10],
                            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'e5e7eb']]],
                        ]);
                    }
                    $gradeTotal[0] += $boys;
                    $gradeTotal[1] += $girls;
                    $gradeTotal[2] += $boys + $girls;
                    $row++;
                }
                // Totals row
                foreach (['A' => 'Total', 'B' => $gradeTotal[0], 'C' => $gradeTotal[1], 'D' => $gradeTotal[2]] as $col => $val) {
                    $sheet->getCell("{$col}{$row}")->setValue($val);
                    $sheet->getStyle("{$col}{$row}")->applyFromArray([
                        'font' => ['bold' => true, 'size' => 10],
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'e0e7ff']],
                        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'c7d2fe']]],
                    ]);
                }
                $row += 3;

                // ── Section 3: By Division ────────────────────────────
                $sheet->mergeCells("A{$row}:G{$row}");
                $sheet->getCell("A{$row}")->setValue('BY DIVISION');
                $sheet->getStyle("A{$row}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 11],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4f46e5']],
                ]);
                $row++;

                foreach (['A' => 'Division', 'B' => 'Boys', 'C' => 'Girls', 'D' => 'Total', 'E' => 'Disabled', 'F' => 'Submitted', 'G' => 'Schools'] as $col => $label) {
                    $sheet->getCell("{$col}{$row}")->setValue($label);
                    $sheet->getStyle("{$col}{$row}")->applyFromArray([
                        'font' => ['bold' => true, 'color' => ['rgb' => 'ffffff'], 'size' => 10],
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '6366f1']],
                        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'ffffff']]],
                    ]);
                    $sheet->getColumnDimension($col)->setWidth(18);
                }
                $row++;

                Division::when($divId, fn($q) => $q->where('id', $divId))->orderBy('name_en')->get()
                    ->each(function ($div) use ($sheet, &$row, $boyCols, $girlCols, $allCols, $academicYear) {
                        $ids     = School::where('division_id', $div->id)->where('is_active', true)->pluck('id');
                        $sumExpr = implode(', ', array_map(fn($c) => "COALESCE(SUM($c),0) as $c", $allCols));
                        $s       = SchoolStat::whereIn('school_id', $ids)
                            ->when($academicYear, fn($q) => $q->where('academic_year', $academicYear))
                            ->selectRaw($sumExpr)->first();
                        $boys  = $s ? collect($boyCols)->sum(fn($c)  => $s->$c) : 0;
                        $girls = $s ? collect($girlCols)->sum(fn($c) => $s->$c) : 0;
                        $sub   = SchoolStat::whereIn('school_id', $ids)
                            ->when($academicYear, fn($q) => $q->where('academic_year', $academicYear))
                            ->distinct('school_id')->count('school_id');
                        $bg = $row % 2 === 0 ? 'f0f4ff' : 'ffffff';
                        foreach ([
                            'A' => $div->name_en,
                            'B' => $boys,
                            'C' => $girls,
                            'D' => $boys + $girls,
                            'E' => $s ? ($s->disabled_boys + $s->disabled_girls) : 0,
                            'F' => $sub . '/' . $ids->count(),
                            'G' => $ids->count(),
                        ] as $col => $val) {
                            $sheet->getCell("{$col}{$row}")->setValue($val);
                            $sheet->getStyle("{$col}{$row}")->applyFromArray([
                                'fill'    => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $bg]],
                                'font'    => ['size' => 10],
                                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'e5e7eb']]],
                            ]);
                        }
                        $row++;
                    });

                // ── Freeze header ─────────────────────────────────────
                $sheet->freezePane('A5');
            },
        ];
    }
}